apigee/microgateway-config

lib/network.js

Fixes #3.
Depends on https://github.com/apigee-internal/microgateway/pull/41 .

Allowing configuration of all URLs.  Allowing user-defined config values.

---

lib/network.js

Dependency changes for localproxy mode. These are required to make the feature work.

Localproxy changes.

---

lib/apid.js
tests/deployments_current.js

apigee-internal/microgateway-core#65

Fixes for issue 65

---

lib/network.js

check response statusCode when pulling configuration from the control plane.

check status code

---

lib/network.js

Add public_key,product_to_proxy,product_to_api_resource to config
object of custom plugin with name specified in
edgemicro.plugins.custom_auth closes apigee/microgateway-config#50

Add properties to custom plugin

---

package.json
tests/get.unit.test.js

now -> shutdown error reporting while running covered coded. Restore at callback.

Changes to test

---

.jshintrc
.travis.yml
index.js
lib/io.js
lib/network.js
npm-shrinkwrap.json
package.json

These are the code quality changes that have been requested.
Review changes to configs. And, there are changes for code quality.
Many changes are similar to the following: '===' instead of '=='.
Unused variables are commented out. Actual deletions have not been done.

For302quality

---

lib/network.js
package.json
tests/get.unit.test.js

fixed jshint-stylish move from dependencies to dev

fix the absence of env in subroutines

---

index.js
lib/io.js
lib/network.js

Exporing new function setConsoleLogger, This function is to be called from cli to set console logger from core.
Updating console logs to call writeConsoleLog.

Updating console logs to use centralized logging

---

lib/default-validator.js
tests/defaultValidator.unit.test.js

config validation should allow bufferSize == 0

Allow zero bufferSize

---

lib/default-validator.js

Add trace and debug levels for validation when microgateway starts

139064652 add debug and trace levels

---

lib/io.js
lib/network.js

Implement centralized console Logger in Microgateway Config project.

Update Console Logs into New Format.

---

lib/default-validator.js
tests/defaultValidator.unit.test.js
tests/fixtures/load-victorshaw-eval-test-config.yaml

Update default-validator tests
Add tests for failOpen,useDebugMpId,useRedis

Fix bug 145722847 and update code coverage

---

lib/network.js

Set timeout property on proxy if timeout is available in targetEndpoint properties

Fix bug 142496489 and set timeout on proxy

---

lib/default-validator.js

Add assert statements for  config.edgemicro.keep_Alive_Timeout and config.edgemicro.headers_Timeout attributes - Issue /b/146320620

Add assert statements

---

lib/default-validator.js

Remove validation on config.edge_config.proxy if not set and proxy_tunnel is set

Fix bug 146069701

---

lib/default-validator.js

Check if 'excludeUrls' type is 'string'.
Check if 'disableExcUrlsCache' type is 'boolean'.

Add validation to excludeUrls

---

lib/default-validator.js
tests/defaultValidator.unit.test.js

Replace env variables in config with actual value during validation.

156560067 Merge Env Values in config.

---

index.js
lib/network.js
lib/redisClient.js

Export redis client to enable usage in other modules.
Add option to enable connection retry.

158618994 Export redis client

---

lib/network.js

Add jwk_public_keys to redis if synchronizerMode is enabled.
Fetch jwk_public_keys from redis if redisBasedConfigCache is set to true.

166517190 Add jwk public keys to redis.

---

npm-shrinkwrap.json
package.json

Update apigeetool version to 0.14.2

Update apigeetool version

---

lib/default-validator.js

142808699-accesscontrol allow deny issue for ip not in allow and deny list.
Add below config variable under accesscontrol plugin
Add validation for noRuleMatchAction
accesscontrol:
noRuleMatchAction: deny

142808699 Fix accesscontrol plugin for allow-deny issues

---

lib/default-validator.js
lib/network.js

Add scopes details to cache config file for custom plugins usage.

170708611 Add scopes details to cache config file

---

lib/default-validator.js

Added new config variable 'enable_GET_req_body' which is optional
Added validation for the config variable if specified, value of this config needs to be of boolean type only

179366445 Add support for GET requests with body

---

lib/default-validator.js

Added validation for ’to_console’ under logging in the config yaml to check for boolean value

183990345 Fix logging to console issue in docker

---

package.json

Upgrade dependency
apigeetool@^0.15.1
resolve@^1.20.0
redis@^3.1.2
mocha@^9.0.1
nyc@^15.1.0

188490428,191241517 Fix security vulnerability

---

lib/default-validator.js

Added validation for target_response_on_abort config

192799989 Make target response behaviour configurable on abort

---

lib/default-validator.js
lib/network.js

- Introduced the new config "isHTTPStatusTooManyRequestEnabled" under quotas
- Added validation for "isHTTPStatusTooManyRequestEnabled" to only allow boolean value

138622990 Make response status code configurable on quota violation

---

lib/network.js

optimised code to add additional checks

Internal cleanup
